### DISCUSSION TITLE
How to add support for prometheus?

### DISCUSSION THREAD

**Discussion by bjorntj** [streamshub/console#1353] [Q&A] [answered]
When running the console, the following errors appears:

"Prometheus can't be reached, or is not configured. Please check your configuration."

So I am trying to configure the instance with prometheus support but I can not find any examples on how to do this. What I can find, is a mentioning of adding this:   metricsSources: [
  ], 
under spec but I am sure what this array should contain?

 Also, the IDE is complaining when adding metricSources so not sure if this is supported yet?

**Comment by MikeEdgar** [comment, marked as answer]
@bjorntj, the `metricsSources` should work in v0.5.0, together with a `metricsSource: <name>` specified on the `kafkaClusters` entry. Below is a template for the `metricsSources` and how to reference one of them. 

If you are in OpenShift with user workload monitoring enabled, you can use the `openshift-monitoring` type. The `embedded` type will deploy a Prometheus in the same namespace as the console deployment with configuration to scrape all Strimzi Kafka clusters in the Kube cluster (intended for development/testing scenarios). Otherwise, the `standalone` type allows you to reference an existing Prometheus and optionally provide credentials. The upcoming 0.6.0 release will also allow for a CA/trusted certificate configuration in case you have self-signed certs protecting your Prometheus endpoint.

```yaml
metricsSources:
 - name: my-prometheus
   type: <one of 'embedded', 'standalone', or 'openshift-monitoring'>
   url: <url to the Prometheus host, only for 'standalone'>
   authentication:
     # optional, only if needed for 'standalone'
     username: <for the prometheus api>
     password: <for the prometheus api>
kafkaClusters:
  - name: my-kafka
    metricsSource: my-prometheus
    # other kafka configurations
```

As far as the IDE error/warning you have, I'm not entirely sure about that. Is the IDE using the CRD somehow for validation?

**Reply by bjorntj** [reply]
I am using Intellij IDEA with the kubernetes plugin and it connects to the cluster and downloads metainfo to be able to validate the yaml files.

btw, when you say version 0.5.0, where can I check the version? I am using the operator "Streams for Apache Kafka Console
2.8.0-13 provided by Red Hat" but not able to find any other version number for the instance.

**Reply by MikeEdgar** [reply]
Ah, ok. Streams for Apache Kafka 2.8.0 is based on the StreamsHub 0.3.6 console. You would see that in the console-api container logs, but not anywhere in the UI. In that case, the `metricsSources` are not yet available. That version should deploy the `embedded` type Prometheus, however.

**Reply by bjorntj** [reply]
How can I change this to use the latest version?

**Reply by MikeEdgar** [reply]
We publish a catalog to `quay.io/streamshub/console-operator-catalog` where you can use the `snapshot-main` tag for the absolute latest on the `main` branch. The `latest` tag is currently pointed to the last `0.3` release, which is probably not what you want. You can create a catalog source with that image with the resources under `/install/operator-olm`. This is the process described by these instructions [1] (but update the image tag first in the `010-CatalogSource-console-operator-catalog.yaml` file.

[1] https://github.com/streamshub/console?tab=readme-ov-file#deploy-the-operator-with-olm

**Reply by bjorntj** [reply]
I must be doing something wrong, I get the following error:

```
resources:
    - group: operators.coreos.com
      kind: CatalogSource
      name: streamshub-console-catalog
      namespace: kafka
      status: Synced
      version: v1alpha1
    - group: operators.coreos.com
      health:
        message: |
          1: CatalogSourcesUnhealthy | True
          2: ResolutionFailed | True
        status: Degraded
      kind: Subscription
      name: kafka-console-operator
      namespace: openshift-operators
      status: Synced
      version: v1alpha1
```

I am not using the operator group yaml file, but the 2 other looks like this:

```
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: streamshub-console-catalog
spec:
  displayName: StreamsHub
  image: quay.io/streamshub/console-operator-catalog:snapshot-main
  publisher: StreamsHub
  sourceType: grpc
```

and the subscription:

```
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: kafka-console-operator
  namespace: openshift-operators
spec:
  name: streamshub-console-operator
  channel: {{ .Values.channel }}
  installPlanApproval: Automatic
  source: streamshub-console-catalog
  sourceNamespace: kafka
  config:
    resources:
      requests:
        cpu: 200m
        memory: 384Mi
      limits:
        memory: {{ .Values.memory_limit }}
        cpu: {{ .Values.cpu_limit }}
```

where .Values.channel = alpha

**Reply by MikeEdgar** [reply]
Is there a `status` on the `CatalogSource` or a pod for it running in the `kafka` namespace?

**Reply by bjorntj** [reply]
Yes, there is a pod named: streamshub-console-catalog-9zrg5 that is status Running.

**Reply by bjorntj** [reply]
Found more error messages:

CatalogSource health unknown
This operator cannot be updated. The health of CatalogSource "streamshub-console-catalog" is unknown. It may have been disabled or removed from the cluster.

**Reply by MikeEdgar** [reply]
Did you modify the `Subscription` from your earlier installation or is that a new resource? If it's the same one I'm wondering if it's unable to switch from one catalog to the other.

**Reply by bjorntj** [reply]
I modified it but I can try to delete all the old resources...

**Reply by MikeEdgar** [reply]
Yeah, I would try that. Especially since both operators will want to manage the Console CRs, so they will race/conflict with each other.

**Reply by bjorntj** [reply]
I still get the same error. The catalog pod seems to be running ok but the operator is not able to get the the health of the catalog pod.

**Reply by bjorntj** [reply]
btw, I see that the catalog pod is running in a different namespace than the operator, would that result is this error perhaps?

**Reply by MikeEdgar** [reply]
What does the `status` of the `CatalogSource` contain?

**Reply by MikeEdgar** [reply]
> btw, I see that the catalog pod is running in a different namespace than the operator, would that result is this error perhaps?

There are some restrictions around namespaces, but I can't recall exactly what they are. You might try putting both of them in the `kafka` namespace.

**Reply by bjorntj** [reply]
The Status of CatalogSource is this:

```
status:
  containerStatuses:
    - restartCount: 0
      started: true
      ready: true
      name: registry-server
      state:
        running:
          startedAt: '2025-01-10T14:22:12Z'
      imageID: 'quay.io/streamshub/console-operator-catalog@sha256:4d74e0d063c30563f4abfb511259cd1b951d75122f8c00919e5c2669fede9663'
      image: 'quay.io/streamshub/console-operator-catalog:snapshot-main'
      lastState: {}
      containerID: 'cri-o://7ab11fbe420c11fe23282beb8f289737e7ae6734f7f56a9e902cb052789c84cd'
```

I tried to put them in the kafka namespace but then I get the error:

"OwnNamespace InstallModeType not supported, cannot configure to watch own namespace"

which is why I tried to install the operator in a different namespace.

**Reply by MikeEdgar** [reply]
Ah, ok. You must already have an `OperatorGroup` in that namespace, maybe for Strimzi. I think that is the status for the catalog `Pod`. There should be a status in the `CatalogSource` itself with some information about readiness of the catalog.

Something like this:
```yaml
status:
  connectionState:
    address: 'console-catalog.streams-console.svc:50051'
    lastConnect: '2025-01-10T14:25:44Z'
    lastObservedState: READY
  latestImageRegistryPoll: '2025-01-10T14:09:58Z'
  registryService:
    createdAt: '2024-12-13T18:27:01Z'
    port: '50051'
    protocol: grpc
    serviceName: console-catalog
    serviceNamespace: streams-console
```

**Reply by bjorntj** [reply]
Yes, that is why I skipped the operator group yaml file.. 😊

But after changing the namespaces back and forth, I suddenly have a running opertator:

"Installed version
streamshub-console-operator.v0.6.0-snapshot"

😎

**Reply by bjorntj** [reply]
Or it was running ok for awhile, then back to this error:

CatalogSource health unknown
This operator cannot be updated. The health of CatalogSource "streamshub-console-catalog" is unknown. It may have been disabled or removed from the cluster.

**Reply by bjorntj** [reply]
The Status for CatalogSource is this:

```
status:
  connectionState:
    address: 'streamshub-console-catalog.kafka.svc:50051'
    lastConnect: '2025-01-10T14:37:27Z'
    lastObservedState: READY
  registryService:
    createdAt: '2025-01-10T14:36:30Z'
    port: '50051'
    protocol: grpc
    serviceName: streamshub-console-catalog
    serviceNamespace: kafka
```

**Reply by MikeEdgar** [reply]
Darn! You get that error on the `Subscription` that's in `openshift-operators`?

**Reply by bjorntj** [reply]
Yes... But that status column under Installed operators, says Succeeded, so they do not agree...

**Reply by MikeEdgar** [reply]
I'm trying to replicate it in my cluster - stand by

**Reply by MikeEdgar** [reply]
Ok, so I think the limitation around namespaces is that a Subscription must reference a CatalogSource in the same namespace, unless the CatalogSource is in a global namespace, which for OpenShift is configured as `openshift-marketplace`. You may not want to put your CatalogSource in that namespace, so perhaps a new namespace just for the console install to place both the Subscription and it's CatalogSource? You'll of course need the OperatorGroup in that case too.

**Reply by bjorntj** [reply]
Ok, I can try to install this in a kafka-console namespace.

**Reply by bjorntj** [reply]
Quick question, the sourceNamespace is that the namespace the catalogsource is running or what should this really points to?

**Reply by bjorntj** [reply]
ok, the operator failes because is clashes with another operator, providing the same API:

Operator failed
intersecting operatorgroups provide the same apis.

The operator it crashes with, is Streams for Apache Kafka, but I am not able to see that they provide the same API.

**Reply by bjorntj** [reply]
The pros is that the subscription is now working.. 😊

**Reply by bjorntj** [reply]
Should I create a namespace called kafka-console-operator to run the operator in and set watch a namespace called kafka-console, instead of watch all or watch kafka namespace?

**Reply by MikeEdgar** [reply]
> Quick question, the sourceNamespace is that the namespace the catalogsource is running or what should this really points to?

Yes, that is the namespace of the CatalogSource

> ok, the operator failes because is clashes with another operator, providing the same API

It must be the Streams for Apache Kafka Console. Is that possibly still installed somewhere? Check for Subscription or ClusterOperatorVersion resources.

You can do a single namespace. The operator actually only supports watching all namespaces. The single namespace approach is generally avoided due to the cluster-scoped nature of CRDs anyway.

**Reply by bjorntj** [reply]
I get the same failed status for Streams for Apache Kafka, that's why I thought they ere crashing in each other (this happend after the latest changes to the kafka-console operator.

I can not find any trace after the old kafka-stream console but for some reasons, I now have 3 operator for Streams for Apache Kafka, one in ns kafka, on in ns openshift-operators and one in ns kafka-console. The one in ns kafka is the one that should be there and it is the other two that fails..

**Reply by MikeEdgar** [reply]
If there aren't any `Subscriptions` for the Streams for Apache Kafka Console operator, double check that there are no `ClusterServiceVersion` resources either. Those are created by the subscription so if you see the operator still installed in the UI for example, that would explain it.

**Reply by bjorntj** [reply]
Yes, I found an old version in ns openshift-operators after trying to search for stream instead of kafka. Deleting that one (and the 2 versions of kafka) seems to have made my day. So far I am now having av running operator for the kafka console. 🙂

**Reply by MikeEdgar** [reply]
Excellent! Now you should be able to use the `metricsSources` configurations posted earlier in the discussion.

**Reply by bjorntj** [reply]
Yes, will try that later tonight.. 

But thx for great help! 🙂

**Reply by bjorntj** [reply]
ok, one last question, hopefully...
Do you see anything wrong with this config?

```
apiVersion: console.streamshub.github.com/v1alpha1
kind: Console
metadata:
  name: kafka-console
  namespace: kafka
spec:
  hostname: {{ .Values.route_hostname }}
  metricsSources:
    - name: ocp-prometheus
      type: openshift-monitoring
  kafkaClusters:
    - name: secure
      namespace: kafka
      listener: plain
      metricsSource: ocp-prometheus
```

I get this error:

```
status:
  conditions:
    - lastTransitionTime: '2025-01-10T16:37:43.751550144Z'
      message: Console resource configuration is invalid
      reason: InvalidConfiguration
      status: 'False'
      type: Ready
  observedGeneration: 2
```

**Reply by MikeEdgar** [reply]
Nothing is jumping out to me, maybe it isn't finding the openshift-monitoring `Route`, but I would expect to see an `Error` condition in addition to the `Ready` condition. Check the operator pod logs too. It looks like the error handling needs to be improved for whatever problem is being encountered.

**Reply by bjorntj** [reply]
Hmmm... I've been out driving and when I got back, the pod (with kafka-console) was up and running... Not sure why... 🙂

**Reply by MikeEdgar** [reply]
Interesting, is the `observedGeneration` still `2` in the Console CR status?

**Reply by bjorntj** [reply]
Yes, still 2:

```
status:
  conditions:
    - lastTransitionTime: '2025-01-10T16:39:15.053097306Z'
      message: All resources ready
      status: 'True'
      type: Ready
  observedGeneration: 2
```

**Reply by bjorntj** [reply]
Is this a known bug or something else? 
When I try to open a topic and list messages, the following exception is logged:

```
Caused by: org.apache.kafka.common.KafkaException: java.lang.NoClassDefFoundError: Could not initialize class com.github.luben.zstd.ZstdInputStreamNoFinalizer
at org.apache.kafka.common.compress.ZstdFactory.wrapForInput(ZstdFactory.java:70)
at org.apache.kafka.common.record.CompressionType$5.wrapForInput(CompressionType.java:155)
at org.apache.kafka.common.record.DefaultRecordBatch.recordInputStream(DefaultRecordBatch.java:273)
at org.apache.kafka.common.record.DefaultRecordBatch.compressedIterator(DefaultRecordBatch.java:277)
at org.apache.kafka.common.record.DefaultRecordBatch.streamingIterator(DefaultRecordBatch.java:358)
at org.apache.kafka.clients.consumer.internals.CompletedFetch.nextFetchedRecord(CompletedFetch.java:223)
at org.apache.kafka.clients.consumer.internals.CompletedFetch.fetchRecords(CompletedFetch.java:274)
... 49 more
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.github.luben.zstd.ZstdInputStreamNoFinalizer
at org.apache.kafka.common.compress.ZstdFactory.wrapForInput(ZstdFactory.java:68)
... 55 more
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.ExceptionInInitializerError: Cannot unpack libzstd-jni-1.5.6-3: Read-only file system [in thread "executor-thread-1"]
at java.base/java.io.UnixFileSystem.createFileExclusively(Native Method)
at java.base/java.io.File.createTempFile(File.java:2170)
at com.github.luben.zstd.util.Native.load(Native.java:130)
at com.github.luben.zstd.util.Native.load(Native.java:86)
at com.github.luben.zstd.ZstdInputStreamNoFinalizer.<clinit>(ZstdInputStreamNoFinalizer.java:23)
```

**Reply by MikeEdgar** [reply]
I haven't see that one before, but judging from the error it's a compressed topic? I understand what the issue is, so I'll look at how we can fix it.

**Reply by bjorntj** [reply]
Yes, it is.

**Reply by bjorntj** [reply]
btw, under Cluster overview, is says Online brokers 0/0 (but there is 3 online).
And under Brokers, all 3 are listed as not running but as far as I can see, all 3 are running. 🙂

**Reply by MikeEdgar** [reply]
> btw, under Cluster overview, is says Online brokers 0/0 (but there is 3 online). And under Brokers, all 3 are listed as not running but as far as I can see, all 3 are running. 🙂

For this one, double check that the Kafka metrics are in the OCP Prometheus instance. For example, the metric `kafka_server_kafkaserver_brokerstate`. These are the metrics you can see in the OCP UI under Observe/Metrics.

**Reply by bjorntj** [reply]
ok, will check,. I see I get the following under Topics stats and guess that is also related:

"Topic metrics are not available for this cluster or no topic activity found. Please check your configuration."

**Reply by MikeEdgar** [reply]
Yeah, I'm not surprised by that either, given the other error. Also double check that the YAML in the console's configuration secret includes the URL to the Thanos Querier route. It should have it, given that the CR was reconciled, but good to check.

Also, just to confirm you have user workload monitoring enabled? https://docs.openshift.com/container-platform/4.17/observability/monitoring/enabling-monitoring-for-user-defined-projects.html

**Reply by bjorntj** [reply]
Yes, there is an URL to "https://thanos-querier-openshift-monitoring.apps...."

And yes, that one is enabled. At least I see the following:

```
oc -n openshift-user-workload-monitoring get pod
NAME                                   READY   STATUS    RESTARTS   AGE
prometheus-operator-6766798cc5-kxm7n   2/2     Running   0          18d
prometheus-user-workload-0             6/6     Running   0          18d
prometheus-user-workload-1             6/6     Running   0          18d
thanos-ruler-user-workload-0           4/4     Running   0          18d
thanos-ruler-user-workload-1           4/4     Running   0          18d
```

**Reply by bjorntj** [reply]
btw,  under Observability and Metrics, I am not able to find any metrics for kafka_server_kafkaserver_brokerstate but I can find for kafka_brokers and kafka_broker_info for instance.

**Reply by MikeEdgar** [reply]
Do you have a configmap like the example for your kafka cluster? It would be referenced from the `Kafka` CR under `.spec.kafka.metricsConfig`

https://github.com/streamshub/console/blob/ae7326e698526eccac3eb72a5bcb8a494d1b1f04/examples/kafka/010-ConfigMap-console-kafka-metrics.yaml

**Reply by bjorntj** [reply]
Guess it is this one?

```
metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          key: kafkaMetrics
          name: secure-metricsconfig
```

**Reply by bjorntj** [reply]
And I see inside the config map, there is only a few zookeeper rules.. So I guess that is the reason for missing metrics..

**Reply by MikeEdgar** [reply]
You may be able to work around that exception for the messages screen adding this to your Console CR. Note it's just a work-around and it will be properly fixed shortly.

```yaml
spec:
  env:
  - name: JAVA_OPTS_APPEND
    value: "-Djava.io.tmpdir=/deployments/work"
```

**Reply by bjorntj** [reply]
Not quite the same exception but almost, after applying the fix:

```
at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.apache.kafka.common.KafkaException: java.lang.ExceptionInInitializerError: Cannot unpack libzstd-jni-1.5.6-3: Read-only file system
at org.apache.kafka.common.compress.ZstdFactory.wrapForInput(ZstdFactory.java:70)
at org.apache.kafka.common.record.CompressionType$5.wrapForInput(CompressionType.java:155)
at org.apache.kafka.common.record.DefaultRecordBatch.recordInputStream(DefaultRecordBatch.java:273)
at org.apache.kafka.common.record.DefaultRecordBatch.compressedIterator(DefaultRecordBatch.java:277)
at org.apache.kafka.common.record.DefaultRecordBatch.streamingIterator(DefaultRecordBatch.java:358)
at org.apache.kafka.clients.consumer.internals.CompletedFetch.nextFetchedRecord(CompletedFetch.java:223)
at org.apache.kafka.clients.consumer.internals.CompletedFetch.fetchRecords(CompletedFetch.java:274)
... 49 more
Caused by: java.lang.ExceptionInInitializerError: Cannot unpack libzstd-jni-1.5.6-3: Read-only file system
at java.base/java.io.UnixFileSystem.createFileExclusively(Native Method)
at java.base/java.io.File.createTempFile(File.java:2170)
at com.github.luben.zstd.util.Native.load(Native.java:130)
at com.github.luben.zstd.util.Native.load(Native.java:86)
at com.github.luben.zstd.ZstdInputStreamNoFinalizer.<clinit>(ZstdInputStreamNoFinalizer.java:23)
at org.apache.kafka.common.compress.ZstdFactory.wrapForInput(ZstdFactory.java:68)
... 55 more
```

**Reply by MikeEdgar** [reply]
This should work instead - I misinterpreted how the `JAVA_OPTS_APPEND` is used.

```yaml
spec:
  env:
  - name: JAVA_OPTS
    value: "-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager -Djava.io.tmpdir=/deployments/work"
```
