### DISCUSSION TITLE
Upgrading the operator?

### DISCUSSION THREAD

**Discussion by bjorntj** [streamshub/console#1385] [Q&A]
Seems like upgrading is not yet included in the operator, what is the best way to upgrade the operator at the moment?

**Comment by MikeEdgar** [comment]
Which catalog source image tag are you using? Upgrades should work.

**Reply by bjorntj** [reply]
I am using latest.

**Reply by MikeEdgar** [reply]
Ok, that's correct then. That should have version 0.6.1 as the latest, along with upgrade paths from 0.5.0 and 0.6.0. What does your Subscription look like?

**Reply by jankalinic** [reply]
I can confirm, from catalog 0.6.1 (latest) you can go from operator version 0.5.0 up to 0.6.1. Note that they are all in the alpha channel.
<img width="899" alt="image" src="https://github.com/user-attachments/assets/be25afbe-57b9-4544-be17-96cb55d8ed2e" />

**Reply by bjorntj** [reply]
Under Subscription, it says installed version is:

streamshub-console-operator.v0.6.0-snapshot

So that is what got me wondering..

**Reply by bjorntj** [reply]
Also, if I do a search for the operator and open that page, I do not have version 0.6.1 inside the Version dropdown menu, only 0.5.0 and 0.6.0-snapshot

**Reply by MikeEdgar** [reply]
Ah, that is probably left from our discussion last week where you were using the `snapshot-main` version of the catalog. You should be able to delete that version and re-install with `latest` or `0.6.1`.

**Reply by bjorntj** [reply]
But I already have done that, I have the following line in my catalog yml file:

image: quay.io/streamshub/console-operator-catalog:latest

**Reply by bjorntj** [reply]
And the status for the streamshub-console-catalog pod, is this:

```
status:
  containerStatuses:
    - restartCount: 0
      started: true
      ready: true
      name: registry-server
      state:
        running:
          startedAt: '2025-01-17T13:33:31Z'
      imageID: 'quay.io/streamshub/console-operator-catalog@sha256:65445e6b88621070483c9b298519a5a9f76db9839882b38188b77998c99f6efa'
      image: 'quay.io/streamshub/console-operator-catalog:latest'
      lastState: {}
      containerID: 'cri-o://4c58c4fb30261db7e99cb1071399cd3183b221d55a38dde4116ca8c7171e4a98'
```
