### DISCUSSION TITLE
This page is temporarily unavailable

### DISCUSSION THREAD

**Discussion by bjorntj** [streamshub/console#1388] [Q&A]
When I open a topic and try to look at messages inside the topic, this error appears instead:

An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.

Not sure why?

**Comment by bjorntj** [comment]
Has it something to do with permissions issue? That the user have no rights to look at this?

I have previously used a user that have "superuser" access but I am now trying to use the same user that developers use to read and write to kafka.

**Reply by MikeEdgar** [reply]
You shouldn't see an error like that for a permission issue, so maybe a bug. Do the `container-api` or `container-ui` logs have anything about the error?

**Reply by bjorntj** [reply]
Are you thinking about the logs for the kafka-console pod or something else here?

**Reply by MikeEdgar** [reply]
Yep, the console pod. It has two containers, so either could have something interesting about the problem.

**Reply by bjorntj** [reply]
no, nothing is logged.. only thing that is logged, is REST APIs with http status 200...

**Reply by MikeEdgar** [reply]
are any of the REST calls for the `/api/{kafkaId}/topics/{topicId}/records` endpoint? I'm just trying to determine if the UI is failing before or after the call.

**Reply by bjorntj** [reply]
No, I do not think I can see such a call. The last call seems to be:

```
GET /api/kafkas/woR7spYqTtm9KzPyJxLC7Q/topics/p-qMULD1SzywaXrBk2QIsw?fields%5Btopics%5D=name,status,visibility,partitions,numPartitions,authorizedOperations,configs,totalLeaderLogBytes,consumerGroups HTTP/1.1
```

**Reply by MikeEdgar** [reply]
Would it be possible to share your Console CR? I'd like to try and reproduce the issue.

**Reply by bjorntj** [reply]
Sure:

```
apiVersion: console.streamshub.github.com/v1alpha1
kind: Console
metadata:
  name: kafka-console
  namespace: kafka
spec:
  hostname: {{ .Values.route_hostname }}
  metricsSources:
    - name: ocp-prometheus
      type: openshift-monitoring
  kafkaClusters:
    - name: secure
      namespace: kafka
      listener: plain
      metricsSource: ocp-prometheus

```

**Reply by MikeEdgar** [reply]
Do you have more than one topic defined in the Kafka cluster? If it's only one, how was it defined?

**Reply by bjorntj** [reply]
In that cluster, we have many topics. The user I am logged in as, have access to 6 of them..

**Reply by bjorntj** [reply]
Topics are created like this, mostly.. Some are also compacted and some are not:

```
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: no.domain.name.endringslogg
  namespace: kafka
  labels:
    strimzi.io/cluster: secure
spec:
  partitions: 1
  replicas: 3
```

**Reply by MikeEdgar** [reply]
Thanks, that looks pretty typical. I think the next thing we can try is turn up the logging for the UI. There must be some attribute that is unexpected, maybe that will help pinpoint it.

In your CR, can you try adding the `containers` section to set the `LOG_LEVEL` env on the UI container, like this:
```yaml
apiVersion: console.streamshub.github.com/v1alpha1
kind: Console
metadata:
  name: kafka-console
  namespace: kafka
spec:
  containers:
    ui:
      spec:
        env:
          - name: LOG_LEVEL
            value: debug
  hostname: {{ .Values.route_hostname }}
  metricsSources:
    - name: ocp-prometheus
      type: openshift-monitoring
  kafkaClusters:
    - name: secure
      namespace: kafka
      listener: plain
      metricsSource: ocp-prometheus
```
