### ISSUE TITLE
Operator must be granted cluster-monitoring-view for grant to instances

### ISSUE THREAD

**Issue by MikeEdgar** [streamshub/console#1259]
Console operator must itself by granted access to the resources of `cluster-monitoring-view` in order to grant the same to instances, when Openshift cluster monitoring is used.

For reference:
```yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-monitoring-view
  labels:
    app.kubernetes.io/managed-by: cluster-monitoring-operator
    app.kubernetes.io/part-of: openshift-monitoring
rules:
  - verbs:
      - get
    apiGroups:
      - ''
    resources:
      - namespaces
  - verbs:
      - get
      - create
      - update
    apiGroups:
      - monitoring.coreos.com
    resources:
      - prometheuses/api
    resourceNames:
      - k8s
```
