### ISSUE TITLE
Metrics depicted in console are multiplied based on prometheus scraper pods count

### ISSUE THREAD

**Issue by Frawless** [streamshub/console#1464]
**Describe the bug**
It seems that in case user uses Prometheus deployment with multiple pods that are scraping the metrics, which could result into multiple occurrences of specific metric, the console backend simply sums the values and show them to the user. This can lead to different values than are the real ones.

Here is the example of Memory consumption of Kafka cluster with requests/limits configuration set to 5Gi for memory and 3 for CPU:

<img width="591" alt="Image" src="https://github.com/user-attachments/assets/1ee5412a-d30e-4e04-9686-2d1ccfd82f6c" />

<img width="416" alt="Image" src="https://github.com/user-attachments/assets/92c3c96f-e718-4b39-9418-be2173679679" />

**To Reproduce**
1. Install prometheus with multiple replicas
2. Install Kafka
3. Install Console
4. Check the metrics value in Prometheus and in Console

**Expected behavior**
Same values in Grafana and Console UI.

**Screenshots**
Screens are available above

**Additional context**
Tried on OpenShift 4.17 with default Prometheus configuration enhanced by the following lines:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-workload-monitoring-config
  namespace: openshift-user-workload-monitoring
data:
  config.yaml: |
    prometheus:
      externalLabels:
        clusterName: {{ clusterName }}
        prometheus_pod: $(POD_NAME)
      volumeClaimTemplate:
        spec:
          storageClassName: standard-csi
          resources:
            requests:
              storage: 100Gi

```
