### ISSUE TITLE
[Improvement] Add OAuth support for schema registry

### ISSUE THREAD

**Issue by seb2020** [streamshub/console#1535]
Hi,

I am using the console with our AMQ Streams Kafka in OpenShift. I am using Apicurio for the schema registry. For the moment, as the message are serialized, it's not possible de read the topic by the console.

Is this planned to add support for a schema registry for deconding message?

![Image](https://github.com/user-attachments/assets/efb9f2c9-220c-4a9f-8f9f-bd25ae3db0ec)

Thanks

**Comment by MikeEdgar** [comment]
Hi @seb2020 which version of the console are you using? The most recently release version includes support for decoding messages using schemas in Apicurio.

**Comment by seb2020** [comment]
Hi, 

amq-streams-console.v2.9.0-3

Maybe I have miss something

**Comment by MikeEdgar** [comment]
If you are using the operator, there is a section in the Console CR where a schema registry is configured [1] and later referenced for a particular Kafka cluster [2].

For example:
```yaml
schemaRegistries:
  - name: "my-registry"
    url: "http://my-registry.example.com/apis/registry/v2/"
kafkaClusters:
  - name: my-kafka
    schemaRegistry: my-registry
    # ... other configuration for my-kafka
```

[1] https://github.com/streamshub/console/blob/50db9b333a1e01f5027f8bd7d1fef348b3de17e3/examples/console/010-Console-example.yaml#L12
[2] https://github.com/streamshub/console/blob/50db9b333a1e01f5027f8bd7d1fef348b3de17e3/examples/console/010-Console-example.yaml#L24
